name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025-vs2026, macos-latest]
        build-mode: [debug, release]

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC x64
      if: matrix.os == 'windows-2025-vs2026'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Install Conan dependencies
      run: |
        conan install . --output-folder=build/${{ matrix.build-mode }} --build=missing -s build_type=${{ matrix.build-mode == 'debug' && 'Debug' || 'Release' }}

    - name: Configure CMake
      run: cmake --preset=${{ matrix.build-mode }}

    - name: Build
      run: cmake --build --preset=${{ matrix.build-mode }}

    - name: Test
      run: ctest --preset=${{ matrix.build-mode }}
